name: install_shared_actions
description: "Downloads shared_actions from shared repository"

inputs:
  token:
    description: "Token to download the shared actions repository"
    required: true
  tag:
    description: "Tag to checkout"
    required: false
    default: ""
  branch:
    description: "Branch to checkout"
    required: false
    default: "main"

runs:
  using: "composite"
  steps:

    - name: prepare ref
      id: prepare_ref
      shell: bash
      run: |
        tag=$(echo ${{inputs.tag}} | sed 's/refs\/tags\///')
        branch=$(echo ${{inputs.branch}} | sed 's/refs\/heads\///')
        [[ -n "${tag}" ]] && ref="refs/tags/$tag" || ref="refs/heads/$branch"
        echo "ref=${ref}" >> $GITHUB_OUTPUT

    - uses: actions/checkout@v4
      name: Checkout cicd repo
      with:
        repository: EFA-FHB/efa_cicd
        token: ${{ inputs.token }}
        path: efa_cicd
        ref: ${{steps.prepare_ref.outputs.value}}

    - name: install shared actions
      env:
        ACTIONS_TARGET_DIR: ${{github.workspace}}
      shell: bash
      run: efa_cicd/install_shared_actions.sh