name: create_release
description: "Creates a release"

inputs:
  gpg_private_key:
    description: "GPG Private key to import for tag signing"
    required: true
  gpg_passphrase:
    description: "GPG Passphrase to import private-key"
    required: true
  token:
    description: "Token required to trigger the workflow."
    required: true
  draft:
    description: "Indicator of whether or not this release is a draft"
    required: false
  prerelease:
    description: "Indicator of whether or not is a prerelease"
    required: false
  name:
    description: "Name of the release. defaults to tag name"
    required: false
  release_type:
    description: "Indicator of the release type"
    required: true
  release_module_name:
    description: "Indicator of the release module name"
    required: true
  versionFile:
    description: "Version file to update version information"
    required: true
  ngrokToken:
    description: "NGROK-Token for debugging"
    required: false
  ngrokDebugEnable:
    description: "Whether to launch ngrok debugging on step failures"
    required: false
  requiredBranches:
    description: "List of branches allowed to create a release from"
    required: false
  requiredBranchPattern:
    description: "Regex pattern to identify allowed branches to create a release from"
    default: "^release/.+|main$"
    required: false
runs:
  using: "composite"

  steps:

    - name: check version file
      shell: bash
      run: |
        if [[ ! -f "${{github.workspace}}/${{ inputs.release_module_name }}/gradle.properties" ]]; then
          echo >&2 "Required file 'gradle.properties' does not exist!"
          exit 1;
        fi

    - name: check workflow origin
      shell: bash
      if: ${{ inputs.requiredBranches != '' ||  inputs.requiredBranchPattern != '' }}
      run: |
        branch="${{ github.ref_name }}"
        reqBranches="${{ inputs.requiredBranches }}"
        reqBranchPattern="${{ inputs.requiredBranchPattern }}"

        if [[ ${#reqBranches} -gt 0 && ! "${reqBranches}" =~ "${branch}" ]]; then
            echo >&2 "Workflow can only be executed on branches '${reqBranches}'!"
            exit 1;
        fi

        if [[ ! "${branch}" =~ ${reqBranchPattern} ]]; then
            echo >&2 "Workflow can only be executed on branches matching pattern '${reqBranchPattern}'!"
            exit 1;
        fi


    - name: import gpg
      id: import_gpg
      uses: crazy-max/ghaction-import-gpg@v5.0.0
      with:
        gpg_private_key: ${{ inputs.gpg_private_key }}
        passphrase: ${{ inputs.gpg_passphrase }}
        git_config_global: true
        git_user_signingkey: true
        git_commit_gpgsign: true

    - name: calculate tag
      id: tag
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ inputs.token }}
        default_bump: ${{inputs.release_type}}
        dry_run: true
        release_branches: "release.*,hotfix.*,main,development"
        tag_prefix: ${{ format('{0}/v',inputs.release_module_name)}}

    - name: compare current and new version
      shell: bash
      run: |
        orig_version=$(grep -E "version=" ${{ inputs.release_module_name }}/gradle.properties | cut -d "=" -f2)

        IFS="." read -r -a curr_version <<<"$(tr -cd '[0-9.]' <<< $orig_version)"
        IFS="." read -r -a new_version <<< "${{ steps.tag.outputs.new_version }}"

        type=
        if [[ ${new_version[0]} -ge ${curr_version[0]} ]]; then #major update
          type=major
        elif [[ ${type} == "major" && ${new_version[1]} -ge ${curr_version[1]} ]]; then #minor change
          type=minor
        elif [[ ${type} == "minor" && ${new_version[2]} -ge ${curr_version[2]} ]]; then #patch update
          type=patch
        fi

        if [[ ! "${type}" =~ major|minor|patch ]]; then
          echo >&2 "New version ${{ steps.tag.outputs.new_version }} has lower preference than current version ${orig_version}!"
          echo >&2 "It should be the other way around. Maybe you forgot to catchup with main first?"
          exit 1;
        fi

    - name: get old tag version
      id: old_tag_version
      shell: bash
      run: |
        orig_version=$(grep -E "version=" ${{ inputs.release_module_name }}/gradle.properties | cut -d "=" -f2)
        prefix="${{ inputs.release_module_name }}/v"
        echo $prefix$orig_version
        echo "value=$prefix$orig_version" >> $GITHUB_OUTPUT
        
    - name: update gradle.properties
      env:
        newVersion: ${{ steps.tag.outputs.new_version }}
      shell: bash
      run: |
        sed -i -E "s/(version=).*/\1${{env.newVersion}}/" ${{ inputs.release_module_name }}/gradle.properties

    - name: commit tag + version
      shell: bash
      env:
        newTag: ${{steps.tag.outputs.new_tag}}
        newVersion: ${{steps.tag.outputs.new_version}}
        GITHUB_TOKEN: ${{ inputs.token }}
        GIT_AUTHOR_NAME: ${{ steps.import_gpg.outputs.name }}
        GIT_AUTHOR_EMAIL: ${{ steps.import_gpg.outputs.email }}
        GIT_COMMITTER_NAME: ${{ steps.import_gpg.outputs.name }}
        GIT_COMMITTER_EMAIL: ${{ steps.import_gpg.outputs.email }}
      run: |
        git commit -S -m "[github] updated ${{inputs.release_type}} version to ${{ env.newVersion }} for module ${{ inputs.release_module_name }}" -- ${{ inputs.release_module_name }}/gradle.properties
        git tag -sam "[github] created new tag ${{ env.newTag }}" ${{ env.newTag }}
      
    - name: git push
      uses: CasperWA/push-protected@v2.10.0
      with:
        token: ${{ inputs.token }}
        tags: true
        branch: "main"
        debug: true
        force: true

    - name: catchup main => development
      shell: bash
      run: |
        git checkout development
        git pull

    - name: changelog config template
      id: changelog_config_path
      shell: bash
      run: |
        config_path=$(find . -name "changelog-config.json" | head -1)
        echo $config_path
        echo "value=${config_path}" >> $GITHUB_OUTPUT

    - name: Build Changelog
      id: github_release
      uses: mikepenz/release-changelog-builder-action@v3
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      with:
        configuration: ${{steps.changelog_config_path.outputs.value}}
        fromTag: ${{steps.old_tag_version.outputs.value}}
        toTag: ${{steps.tag.outputs.new_tag}}

    - name: Create Release
      uses: softprops/action-gh-release@v0.1.14
      with:
        draft: ${{inputs.draft}}
        prerelease: ${{inputs.draft}}
        name: ${{inputs.name}}
        body: ${{steps.github_release.outputs.changelog}}
        tag_name: ${{steps.tag.outputs.new_tag}}

    - name: hotfix - remove branch
      if: startsWith(github.ref_name, 'hotfix/')
      shell: bash
      run: |
        echo "Deleting hotfix branch ${{ github.ref_name }}"
        git push -d origin ${{ github.ref_name }} &> /dev/null

    - name: Start SSH via Ngrok
      id: start_ngrok
      if: ${{ failure() && inputs.ngrokDebugEnable == 'true' }}
      shell: bash
      run: |
        curl -sL https://gist.githubusercontent.com/retyui/7115bb6acf151351a143ec8f96a7c561/raw/7099b9db76729dc5761da72aa8525f632d8875c9/debug-github-actions.sh | bash
        echo "state=${true}" >> $GITHUB_OUTPUT
      env:
        # After sign up on the https://ngrok.com/
        # You can find this token here: https://dashboard.ngrok.com/get-started/setup
        NGROK_TOKEN: ${{ inputs.ngrokToken }}

        # This password you will use when authorizing via SSH
        # USER_PASS: ${{ secrets.USER_PASS }}
        USER_PASS: debug

    - name: Don't kill instace
      if: ${{ failure() && inputs.ngrokDebugEnable == 'true' }}
      shell: bash
      run: sleep 1h # Prevent to killing instance after failure
