package com.nortal.efafhb.eforms.validator.exception;

public enum ErrorCode {
  BAD_REQUEST,
  TOO_MANY_REQUESTS,
  INVALID_SDK_TYPE,
  BAD_EFORM_VERSION_FORMAT,
  UNKNOWN_ERROR,

  GENERIC_USER_NOTIFICATION,
  MALFORMED_XML,
  NO_VALID_CONTENT_TYPE,
  UNSUPPORTED_EFORM_VERSION_SDK_TYPE,
  METHOD_NOT_ALLOWED,
  VALIDATION_DISABLED
}
