name: Publish package to GitHub Packages
on: push

concurrency: eforms-validator-core-${{github.ref_name}}

jobs:
  test:
    runs-on: ubuntu-latest-8-cores
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: execute tests
        uses: gradle/gradle-build-action@v2.5.1
        with:
          arguments: test
      - name: Run Sonar scan        
        if: ${{ vars.SONAR_SCAN_ENABLED == 'true' }}        
        env: 
          GITHUB_TOKEN: ${{ secrets.EFA_CICD_REPO_ACCESS_TOKEN }}  # Needed to get PR information, if any          
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}          
          SONAR_HOST_URL: https://sonarcloud.io        
        uses: gradle/gradle-build-action@v2        
        with:          
          arguments: sonarqube --info    
  publish:
    
    needs: [test]      
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Publish package
        uses: gradle/gradle-build-action@v2.5.1
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.JAVA_TOKEN }}
          GITHUB_ACTOR: ${{ secrets.JAVA_ACTOR }}
