# This workflow creates a release for the application.
#
name: "🎁 Create Release"

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Specify semver type of release"
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
      release_name:
        description: 'Specify name of release (defaults to tag_name)'
        type: string
      release_module_name:
        description: 'Specify which module to release'
        required: true
        type: choice
        options:
          - app-ext
          - app-int

permissions: write-all
            
concurrency:
  group: release

jobs:

  release:
    runs-on: ubuntu-latest

    steps:

      - name: debug
        shell: bash
        run: |
          echo '${{ toJSON(github) }}'

      - uses: actions/checkout@v3
        name: Checkout project
        with:
          fetch-depth: 0 #spotless fix
          persist-credentials: false

      - name: install_shared_actions
        uses: ./.github/actions/install_shared_actions
        with:
          token: ${{secrets.EFA_CICD_REPO_ACCESS_TOKEN}}
          tag: v2.5.3

      - name: ensure branch strategy compliance
        id: check_branch_strategy
        uses: ./.github/actions/shared/check_branch_name

      - name: create_release
        uses: ./.github/actions/create_release_validator
        with:
          gpg_private_key: ${{secrets.BOT_GPG_PRIVATE_KEY}}
          gpg_passphrase: ${{secrets.BOT_GPG_PASSPHRASE}}
          token: ${{secrets.GITHUB_TOKEN}}
          name: ${{inputs.release_name}}
          release_type: ${{inputs.release_type}}
          versionFile: "gradle.properties"
          ngrokToken: ${{secrets.NGROK_TOKEN}}
          release_module_name: ${{inputs.release_module_name}}
